version: '3.9'

services:
  shortener:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - PG_HOST=postgres
      - SALT="$2b$10$ppHrWgZ096XlSEctzDPYku"
      - PASSWORD=postgres
      - DOCKER=true
    links:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urls
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data:
